name: Snapshot Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Build with Gradle
        run: ./gradlew build shadowJar

      - name: Create or update snapshot release
        uses: softprops/action-gh-release@v2
        with:
          name: Latest Snapshot
          tag_name: snapshot
          files: |
            build/libs/*-all.jar
          draft: false
          prerelease: true
